import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./generated"; // generated by openapi-typescript

export const createApiClient = ({ baseUrl }: { baseUrl: string }) => {
  const fetchClient = createFetchClient<paths>({
    baseUrl,
  });
  const $api = createClient(fetchClient);

  return $api.useQuery("get", "/api/v1/users/{user_id}", {
    params: {
      path: {
        user_id: 1,
      },
    },
  });
};
