import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./generated.d.ts"; // generated by openapi-typescript

export * from "./generated";

export * from "@tanstack/react-query";

export const createApiClient = ({ baseUrl }: { baseUrl: string }) => {
  const fetchClient = createFetchClient<paths>({
    baseUrl,
  });
  const $api = createClient(fetchClient);

  return $api;
};
